//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHook.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHook.Resources.Localization.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above.
        /// </summary>
        internal static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current Bait/Mooch.
        /// </summary>
        internal static string AddCurrentBaitMooch {
            get {
                return ResourceManager.GetString("AddCurrentBaitMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Last Catch:.
        /// </summary>
        internal static string AddLastCatch {
            get {
                return ResourceManager.GetString("AddLastCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Preset.
        /// </summary>
        internal static string AddNewPreset {
            get {
                return ResourceManager.GetString("AddNewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After being caught....
        /// </summary>
        internal static string AfterBeingCaught {
            get {
                return ResourceManager.GetString("AfterBeingCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If this config is a bait: Stops fishing after X amount of fish is caught
        ///- If this config is a fish: Stops fishing after it being caught X amount of times.
        /// </summary>
        internal static string AfterBeingCaughtDescription {
            get {
                return ResourceManager.GetString("AfterBeingCaughtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After X stacks of Anglers Art....
        /// </summary>
        internal static string AfterAnglersArt {
            get {
                return ResourceManager.GetString("AfterAnglersArt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to - If this config is a bait: Stops fishing after X stacks of Anglers Art
        ///- If this config is a fish: Stops fishing after X stacks of Anglers Art.
        /// </summary>
        internal static string AfterAnglersArtDescription {
            get {
                return ResourceManager.GetString("AfterAnglersArtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A preset with the same name already exists.
        /// </summary>
        internal static string APresetWithTheSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("APresetWithTheSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Casts.
        /// </summary>
        internal static string Auto_Casts {
            get {
                return ResourceManager.GetString("Auto_Casts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Priority: Watered-Cordial &gt; Cordial &gt; HI-Cordials.
        /// </summary>
        internal static string AutoCastCordialPriority {
            get {
                return ResourceManager.GetString("AutoCastCordialPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If theres no Cordials, Hi-Cordials will be used instead.
        /// </summary>
        internal static string AutoCastCordialPriorityHelpMarker {
            get {
                return ResourceManager.GetString("AutoCastCordialPriorityHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use when Mooch II is on NOT available - READ &gt;&gt;&gt;.
        /// </summary>
        internal static string AutoCastExtraOptionPrizeCatch {
            get {
                return ResourceManager.GetString("AutoCastExtraOptionPrizeCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Chum.
        /// </summary>
        internal static string AutoCastUseChum {
            get {
                return ResourceManager.GetString("AutoCastUseChum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Cordials (Hi-Cordial First).
        /// </summary>
        internal static string AutoCastUseCordial {
            get {
                return ResourceManager.GetString("AutoCastUseCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If theres no Hi-Cordials, Cordials will be used instead.
        /// </summary>
        internal static string AutoCastUseCordialHelpMarker {
            get {
                return ResourceManager.GetString("AutoCastUseCordialHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fish Eyes.
        /// </summary>
        internal static string AutoCastUseFishEyes {
            get {
                return ResourceManager.GetString("AutoCastUseFishEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;ll only hide if the AutoGig option is disabled.
        /// </summary>
        internal static string AutoGigHideOverlayHelpMarker {
            get {
                return ResourceManager.GetString("AutoGigHideOverlayHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHook.
        /// </summary>
        internal static string AutoHook {
            get {
                return ResourceManager.GetString("AutoHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHook Disabled.
        /// </summary>
        internal static string AutoHook_Disabled {
            get {
                return ResourceManager.GetString("AutoHook_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHook Enabled.
        /// </summary>
        internal static string AutoHook_Enabled {
            get {
                return ResourceManager.GetString("AutoHook_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mooch.
        /// </summary>
        internal static string AutoMooch {
            get {
                return ResourceManager.GetString("AutoMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If this is a Bait (Ex: Versatile Lure), all fish caught by this bait will be mooched
        ///- If this is a Fish/Mooch (Ex: Harbor Herring), it&apos;ll be mooched when caught
        ///- If this option is disabled, the fish will NOT be mooched even if Auto Mooch is also enabled in the general tab.
        /// </summary>
        internal static string AutoMoochPresetDescription {
            get {
                return ResourceManager.GetString("AutoMoochPresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option takes priority over the Auto Cast Line.
        /// </summary>
        internal static string AutoMoochPresetHelpMarker {
            get {
                return ResourceManager.GetString("AutoMoochPresetHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bait already exists.
        /// </summary>
        internal static string BaitAlreadyExists {
            get {
                return ResourceManager.GetString("BaitAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string BaitName_Default {
            get {
                return ResourceManager.GetString("BaitName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below.
        /// </summary>
        internal static string Below {
            get {
                return ResourceManager.GetString("Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels Current Mooch.
        /// </summary>
        internal static string CancelsCurrentMooch {
            get {
                return ResourceManager.GetString("CancelsCurrentMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chum.
        /// </summary>
        internal static string Chum {
            get {
                return ResourceManager.GetString("Chum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chum Timer.
        /// </summary>
        internal static string ChumTimer {
            get {
                return ResourceManager.GetString("ChumTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordial.
        /// </summary>
        internal static string Cordial {
            get {
                return ResourceManager.GetString("Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current bait/mooch:.
        /// </summary>
        internal static string CurrentBaitMooch {
            get {
                return ResourceManager.GetString("CurrentBaitMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid import..
        /// </summary>
        internal static string DecompressString_Invalid_Import {
            get {
                return ResourceManager.GetString("DecompressString_Invalid_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Cast.
        /// </summary>
        internal static string DefaultCast {
            get {
                return ResourceManager.GetString("DefaultCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default hooking behavior if no Custom Preset is found..
        /// </summary>
        internal static string DefaultHookingBehavior {
            get {
                return ResourceManager.GetString("DefaultHookingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Mooch.
        /// </summary>
        internal static string DefaultMooch {
            get {
                return ResourceManager.GetString("DefaultMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default mooching behavior if no Preset is found..
        /// </summary>
        internal static string DefaultMoochingBehavior {
            get {
                return ResourceManager.GetString("DefaultMoochingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important!!!
        ///
        ///If disabled, Precision/Powerful hook will be used instead when Patience is up..
        /// </summary>
        internal static string DHTHPatienceHelpMarker {
            get {
                return ResourceManager.GetString("DHTHPatienceHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables AutoHook.
        /// </summary>
        internal static string Disables_AutoHook {
            get {
                return ResourceManager.GetString("Disables_AutoHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Cancel Mooch.
        /// </summary>
        internal static string Dont_Cancel_Mooch {
            get {
                return ResourceManager.GetString("Dont_Cancel_Mooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Hook.
        /// </summary>
        internal static string Double_Hook {
            get {
                return ResourceManager.GetString("Double_Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double/Triple Hook Settings.
        /// </summary>
        internal static string DoubleTripleHookSettings {
            get {
                return ResourceManager.GetString("DoubleTripleHookSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw fish hitbox.
        /// </summary>
        internal static string DrawFishHitbox {
            get {
                return ResourceManager.GetString("DrawFishHitbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hitbox its only available for the fish of the Size and Speed selected.
        /// </summary>
        internal static string DrawFishHitboxHelpMarker {
            get {
                return ResourceManager.GetString("DrawFishHitboxHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw gig hitbox.
        /// </summary>
        internal static string DrawGigHitbox {
            get {
                return ResourceManager.GetString("DrawGigHitbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the new changes in the Changelog below.
        /// </summary>
        internal static string DrawHeader_CheckChangelog {
            get {
                return ResourceManager.GetString("DrawHeader_CheckChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to report an issue or make a suggestion.
        /// </summary>
        internal static string DrawHeader_ClickToReportAnIssue {
            get {
                return ResourceManager.GetString("DrawHeader_ClickToReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string DrawHeader_GeneralSettings {
            get {
                return ResourceManager.GetString("DrawHeader_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string DrawHeader_Testing {
            get {
                return ResourceManager.GetString("DrawHeader_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DrawImportExport_Cancel {
            get {
                return ResourceManager.GetString("DrawImportExport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditMe.
        /// </summary>
        internal static string EditMe {
            get {
                return ResourceManager.GetString("EditMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Casts.
        /// </summary>
        internal static string Enable_Auto_Casts {
            get {
                return ResourceManager.GetString("Enable_Auto_Casts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AutoGig.
        /// </summary>
        internal static string Enable_AutoGig {
            get {
                return ResourceManager.GetString("Enable_AutoGig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AutoHook.
        /// </summary>
        internal static string Enable_AutoHook {
            get {
                return ResourceManager.GetString("Enable_AutoHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AutoGig.
        /// </summary>
        internal static string EnableAutoGig {
            get {
                return ResourceManager.GetString("EnableAutoGig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Chum Timers.
        /// </summary>
        internal static string EnableChumTimers {
            get {
                return ResourceManager.GetString("EnableChumTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Min/Max times when under the effect of Chum.
        /// </summary>
        internal static string EnableChumTimersHelpMarker {
            get {
                return ResourceManager.GetString("EnableChumTimersHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled Config -&gt;.
        /// </summary>
        internal static string EnabledConfigArrow {
            get {
                return ResourceManager.GetString("EnabledConfigArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important!!!
        ///
        ///If disabled, the fish will NOT be hooked or Mooched.
        ///To use the default behavior (General Tab), please delete this configuration..
        /// </summary>
        internal static string EnabledConfigArrowhelpMarker {
            get {
                return ResourceManager.GetString("EnabledConfigArrowhelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables AutoHook.
        /// </summary>
        internal static string Enables_AutoHook {
            get {
                return ResourceManager.GetString("Enables_AutoHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export preset to clipboard..
        /// </summary>
        internal static string ExportPresetToClipboard {
            get {
                return ResourceManager.GetString("ExportPresetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;Make sure &apos;Use Mooch II&apos; is enabled or else it wont work&lt;
        ///This could save you 100gp if going only for mooches.
        /// </summary>
        internal static string ExtraOptionPrizeCatchHelpMarker {
            get {
                return ResourceManager.GetString("ExtraOptionPrizeCatchHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Eyes.
        /// </summary>
        internal static string Fish_Eyes {
            get {
                return ResourceManager.GetString("Fish_Eyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisher&apos;s Intuition Settings.
        /// </summary>
        internal static string FisherSIntuitionSettings {
            get {
                return ResourceManager.GetString("FisherSIntuitionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Hooks when Fisher&apos;s Intuition is detected.
        /// </summary>
        internal static string FisherSIntuitionSettingsHelpMarker {
            get {
                return ResourceManager.GetString("FisherSIntuitionSettingsHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Auto Cast Line.
        /// </summary>
        internal static string Global_Auto_Cast_Line {
            get {
                return ResourceManager.GetString("Global_Auto_Cast_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Auto Mooch.
        /// </summary>
        internal static string Global_Auto_Mooch {
            get {
                return ResourceManager.GetString("Global_Auto_Mooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        internal static string GP {
            get {
                return ResourceManager.GetString("GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook will be used after the defined amount of time has passed
        ///Min. time: 2s (because of animation lock)
        ///
        ///Set Zero (0) to disable, and dont make this lower than the Min. Wait.
        /// </summary>
        internal static string HelpMarkerMaxWaitTimer {
            get {
                return ResourceManager.GetString("HelpMarkerMaxWaitTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook will NOT be used until the minimum time has passed.
        ///
        ///Ex: If you set the number as 14 and something bites after 8 seconds, the fish will not to be hooked
        ///
        ///Set Zero (0) to disable.
        /// </summary>
        internal static string HelpMarkerMinWaitTimer {
            get {
                return ResourceManager.GetString("HelpMarkerMinWaitTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi-Cordial.
        /// </summary>
        internal static string Hi_Cordial {
            get {
                return ResourceManager.GetString("Hi_Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide overlay during Spearfishing.
        /// </summary>
        internal static string HideOverlayDuringSpearfishing {
            get {
                return ResourceManager.GetString("HideOverlayDuringSpearfishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitbox.
        /// </summary>
        internal static string Hitbox {
            get {
                return ResourceManager.GetString("Hitbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold SHIFT to select both Double and Triple Hook (not recommended).
        /// </summary>
        internal static string HoldShiftBothDHTH {
            get {
                return ResourceManager.GetString("HoldShiftBothDHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold SHIFT to delete..
        /// </summary>
        internal static string HoldShiftToDelete {
            get {
                return ResourceManager.GetString("HoldShiftToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Legendary (!!!).
        /// </summary>
        internal static string HookLegendaryExclamation {
            get {
                return ResourceManager.GetString("HookLegendaryExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Presets.
        /// </summary>
        internal static string HookPresets {
            get {
                return ResourceManager.GetString("HookPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Strong (!!).
        /// </summary>
        internal static string HookStrongExclamation {
            get {
                return ResourceManager.GetString("HookStrongExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Weak (!).
        /// </summary>
        internal static string HookWeakExclamation {
            get {
                return ResourceManager.GetString("HookWeakExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Hook&quot; will be used if Patience is not up.
        /// </summary>
        internal static string HookWillBeUsedIfPatienceIsNotUp {
            get {
                return ResourceManager.GetString("HookWillBeUsedIfPatienceIsNotUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ Cordial.
        /// </summary>
        internal static string HQ_Cordial {
            get {
                return ResourceManager.GetString("HQ_Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ Watered Cordial.
        /// </summary>
        internal static string HQ_Watered_Cordial {
            get {
                return ResourceManager.GetString("HQ_Watered_Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical Cast.
        /// </summary>
        internal static string Identical_Cast {
            get {
                return ResourceManager.GetString("Identical_Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import stack from clipboard..
        /// </summary>
        internal static string ImportStackFromClipboard {
            get {
                return ResourceManager.GetString("ImportStackFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import this preset?.
        /// </summary>
        internal static string ImportThisPreset {
            get {
                return ResourceManager.GetString("ImportThisPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let the fish escape if GP is below the required.
        /// </summary>
        internal static string LetTheFishEscape {
            get {
                return ResourceManager.GetString("LetTheFishEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeShift Bait.
        /// </summary>
        internal static string MakeShift_Bait {
            get {
                return ResourceManager.GetString("MakeShift_Bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Wait.
        /// </summary>
        internal static string MaxWait {
            get {
                return ResourceManager.GetString("MaxWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Wait.
        /// </summary>
        internal static string MinWait {
            get {
                return ResourceManager.GetString("MinWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mooch/Bait Name.
        /// </summary>
        internal static string MoochBaitName {
            get {
                return ResourceManager.GetString("MoochBaitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Preset.
        /// </summary>
        internal static string New_Preset {
            get {
                return ResourceManager.GetString("New_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New bait/mooch.
        /// </summary>
        internal static string NewBaitMooch {
            get {
                return ResourceManager.GetString("NewBaitMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Preset.
        /// </summary>
        internal static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use when Fisher&apos;s Intuition is active.
        /// </summary>
        internal static string OnlyUseWhenFisherSIntutionIsActive {
            get {
                return ResourceManager.GetString("OnlyUseWhenFisherSIntutionIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use when Identical Cast is active.
        /// </summary>
        internal static string OnlyUseWhenIdenticalCastIsActive {
            get {
                return ResourceManager.GetString("OnlyUseWhenIdenticalCastIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Config Window.
        /// </summary>
        internal static string Opens_Config_Window {
            get {
                return ResourceManager.GetString("Opens_Config_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides Identical Cast.
        /// </summary>
        internal static string OverridesIdenticalCast {
            get {
                return ResourceManager.GetString("OverridesIdenticalCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides Surface Slap.
        /// </summary>
        internal static string OverridesSurfaceSlap {
            get {
                return ResourceManager.GetString("OverridesSurfaceSlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patience I.
        /// </summary>
        internal static string Patience_I {
            get {
                return ResourceManager.GetString("Patience_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patience II.
        /// </summary>
        internal static string Patience_II {
            get {
                return ResourceManager.GetString("Patience_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Disabled.
        /// </summary>
        internal static string Plugin_Disabled {
            get {
                return ResourceManager.GetString("Plugin_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Enabled.
        /// </summary>
        internal static string Plugin_Enabled {
            get {
                return ResourceManager.GetString("Plugin_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string Plugin_Name_Settings {
            get {
                return ResourceManager.GetString("Plugin_Name_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables/Disables the plugin for you.
        /// </summary>
        internal static string PluginUi_Draw_Enables_Disables {
            get {
                return ResourceManager.GetString("PluginUi_Draw_Enables_Disables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string PluginUi_Language {
            get {
                return ResourceManager.GetString("PluginUi_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful Hookset.
        /// </summary>
        internal static string PowerfulHookset {
            get {
                return ResourceManager.GetString("PowerfulHookset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision Hookset.
        /// </summary>
        internal static string PrecisionHookset {
            get {
                return ResourceManager.GetString("PrecisionHookset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A preset with the same name already exists.
        /// </summary>
        internal static string PresetAlreadyExist {
            get {
                return ResourceManager.GetString("PresetAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset exported to the clipboard.
        /// </summary>
        internal static string PresetExportedToTheClipboard {
            get {
                return ResourceManager.GetString("PresetExportedToTheClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Name.
        /// </summary>
        internal static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize Catch.
        /// </summary>
        internal static string Prize_Catch {
            get {
                return ResourceManager.GetString("Prize_Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to rename.
        /// </summary>
        internal static string RightClickToRename {
            get {
                return ResourceManager.GetString("RightClickToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Size and Speed of the fish you want (Gatherbuddy&apos;s Spearfishing overlay helps a lot).
        /// </summary>
        internal static string SelectTheSizeAndSpeed {
            get {
                return ResourceManager.GetString("SelectTheSizeAndSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop fishing.
        /// </summary>
        internal static string StopFishing {
            get {
                return ResourceManager.GetString("StopFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop fishing after....
        /// </summary>
        internal static string StopFishingAfter {
            get {
                return ResourceManager.GetString("StopFishingAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me on Ko-fi.
        /// </summary>
        internal static string Support_me_on_Ko_fi {
            get {
                return ResourceManager.GetString("Support_me_on_Ko_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Slap.
        /// </summary>
        internal static string Surface_Slap {
            get {
                return ResourceManager.GetString("Surface_Slap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Slap &amp; Identical Cast.
        /// </summary>
        internal static string SurfaceSlapIdenticalCast {
            get {
                return ResourceManager.GetString("SurfaceSlapIdenticalCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast (FSH Action) will be used after a bite
        ///
        ///IMPORTANT!!!
        ///If Auto Mooch (Global or Custom Preset) is not enabled, the line will be casted normally and you&apos;ll lose your mooch opportunity (If available).
        /// </summary>
        internal static string TabAutoCasts_DrawAutoCast_HelpText {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawAutoCast_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option have priority over Auto Cast Line
        ///
        ///If you want to Auto Mooch only a specific fish and ignore others, disable this option and create a Custom Preset..
        /// </summary>
        internal static string TabAutoCasts_DrawAutoMooch_HelpText {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawAutoMooch_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use when Fisher&apos;s Intuition is active.
        /// </summary>
        internal static string TabAutoCasts_DrawExtraOptionsAutoMooch_Extra_Only_Active {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawExtraOptionsAutoMooch_Extra_Only_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use when Makeshift Bait is active.
        /// </summary>
        internal static string TabAutoCasts_DrawExtraOptionsPatience {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawExtraOptionsPatience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Stacks =.
        /// </summary>
        internal static string TabAutoCasts_DrawExtraOptionsThaliaksFavor_ {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawExtraOptionsThaliaksFavor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide: How to auto accept Collectables.
        /// </summary>
        internal static string TabAutoCasts_DrawHeader_Guide_Collectables {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawHeader_Guide_Collectables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions that cancel mooch wont be used (e.g. Chum, Fish Eyes, Prize Catch etc.).
        /// </summary>
        internal static string TabAutoCasts_DrawHeader_HelpText {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawHeader_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This might conflict with Auto Thaliak&apos;s Favor.
        /// </summary>
        internal static string TabAutoCasts_DrawMakeShiftBait_HelpText {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawMakeShiftBait_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patience I/II will be used when your current GP is equal (or higher) to the action cost +20 (Ex: 220 for I, 580 for II), this helps to avoid not having GP for the hooksets.
        /// </summary>
        internal static string TabAutoCasts_DrawPatience_HelpText {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawPatience_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This might conflict with Auto MakeShift Bait.
        /// </summary>
        internal static string TabAutoCasts_DrawThaliaksFavor_HelpText {
            get {
                return ResourceManager.GetString("TabAutoCasts_DrawThaliaksFavor_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Stacks = .
        /// </summary>
        internal static string TabAutoCasts_When_Stack_Equals {
            get {
                return ResourceManager.GetString("TabAutoCasts_When_Stack_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an experimental feature and it might miss the fish. If you find it missing too much, try adjusting the SpearFishing window scale to something different.
        /// </summary>
        internal static string TabAutoGigDescription {
            get {
                return ResourceManager.GetString("TabAutoGigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help with the plugin localization (Crowdin).
        /// </summary>
        internal static string TabGeneral_DrawHeader_Localization_Help {
            get {
                return ResourceManager.GetString("TabGeneral_DrawHeader_Localization_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can customize the GP Threshold for the actions and items used by the AutoCast feature..
        /// </summary>
        internal static string TabGPConfig_TabDescription {
            get {
                return ResourceManager.GetString("TabGPConfig_TabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoGig.
        /// </summary>
        internal static string TabNameAutoGig {
            get {
                return ResourceManager.GetString("TabNameAutoGig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Presets.
        /// </summary>
        internal static string TabNameCustomPresets {
            get {
                return ResourceManager.GetString("TabNameCustomPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TabnameGeneral {
            get {
                return ResourceManager.GetString("TabnameGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Config.
        /// </summary>
        internal static string TabNameGPConfig {
            get {
                return ResourceManager.GetString("TabNameGPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to correctly edit the bait/mooch name like displayed in-game (Ex: Versatile Lure).
        /// </summary>
        internal static string TabPresets_DrawHeader_CorrectlyEditTheBaitMoochName {
            get {
                return ResourceManager.GetString("TabPresets_DrawHeader_CorrectlyEditTheBaitMoochName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Preset name (press Enter to confirm).
        /// </summary>
        internal static string TabPresets_DrawHeader_EditPresetNamePressEnterToConfirm {
            get {
                return ResourceManager.GetString("TabPresets_DrawHeader_EditPresetNamePressEnterToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is enabled by default when new bait/mooch is added .
        /// </summary>
        internal static string TabPresets_DrawHeader_IsEnabledByDefault {
            get {
                return ResourceManager.GetString("TabPresets_DrawHeader_IsEnabledByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can customize which hook to use based on the current bait or mooch.
        ///If a bait/mooch is not specified, the default behavior (General Tab) will be used instead..
        /// </summary>
        internal static string TabPresets_DrawHeader_TabDescription {
            get {
                return ResourceManager.GetString("TabPresets_DrawHeader_TabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaliak&apos;s Favor.
        /// </summary>
        internal static string Thaliaks_Favor {
            get {
                return ResourceManager.GetString("Thaliaks_Favor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time(s).
        /// </summary>
        internal static string TimeS {
            get {
                return ResourceManager.GetString("TimeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles AutoHook On/Off.
        /// </summary>
        internal static string Toggles_AutoHook_On_Off {
            get {
                return ResourceManager.GetString("Toggles_AutoHook_On_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Hook.
        /// </summary>
        internal static string Triple_Hook {
            get {
                return ResourceManager.GetString("Triple_Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Makeshift Bait.
        /// </summary>
        internal static string Use_Makeshift_Bait {
            get {
                return ResourceManager.GetString("Use_Makeshift_Bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mooch II.
        /// </summary>
        internal static string Use_Mooch_II {
            get {
                return ResourceManager.GetString("Use_Mooch_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Nature&apos;s Bounty.
        /// </summary>
        internal static string Use_Natures_Bounty {
            get {
                return ResourceManager.GetString("Use_Natures_Bounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Patience I/II.
        /// </summary>
        internal static string Use_Patience_I_II {
            get {
                return ResourceManager.GetString("Use_Patience_I_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Prize Catch.
        /// </summary>
        internal static string Use_Prize_Catch {
            get {
                return ResourceManager.GetString("Use_Prize_Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels Current Mooch. Patience and Makeshift Bait will not be used when Prize Catch active.
        /// </summary>
        internal static string Use_Prize_Catch_HelpText {
            get {
                return ResourceManager.GetString("Use_Prize_Catch_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Thaliak&apos;s Favor.
        /// </summary>
        internal static string Use_Thaliaks_Favor {
            get {
                return ResourceManager.GetString("Use_Thaliaks_Favor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Cast.
        /// </summary>
        internal static string UseDefaultCast {
            get {
                return ResourceManager.GetString("UseDefaultCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Mooch.
        /// </summary>
        internal static string UseDefaultMooch {
            get {
                return ResourceManager.GetString("UseDefaultMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Double Hook (If gp &gt; 400).
        /// </summary>
        internal static string UseDoubleHookIfGp400 {
            get {
                return ResourceManager.GetString("UseDoubleHookIfGp400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Identical Cast.
        /// </summary>
        internal static string UseIdenticalCast {
            get {
                return ResourceManager.GetString("UseIdenticalCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mooch II.
        /// </summary>
        internal static string UseMoochII {
            get {
                return ResourceManager.GetString("UseMoochII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Surface Slap.
        /// </summary>
        internal static string UseSurfaceSlap {
            get {
                return ResourceManager.GetString("UseSurfaceSlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Triple Hook (If gp &gt; 700).
        /// </summary>
        internal static string UseTripleHookIfGp700 {
            get {
                return ResourceManager.GetString("UseTripleHookIfGp700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use when Patience is active (not recommended).
        /// </summary>
        internal static string UseWhenPatienceIsActiveNotRecommended {
            get {
                return ResourceManager.GetString("UseWhenPatienceIsActiveNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Chum timer.
        /// </summary>
        internal static string Using_Chum_Timer {
            get {
                return ResourceManager.GetString("Using_Chum_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watered Cordial.
        /// </summary>
        internal static string Watered_Cordial {
            get {
                return ResourceManager.GetString("Watered_Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be used when your GP is Equal or.
        /// </summary>
        internal static string WillBeUsedWhenYourGPIsEqualOr {
            get {
                return ResourceManager.GetString("WillBeUsedWhenYourGPIsEqualOr", resourceCulture);
            }
        }
    }
}
